[package]
name         = "sema-engine"
version      = "0.12.1"
edition      = "2024"
rust-version = "1.85"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/LiGoldragon/sema-engine"
description  = "Typed database operation engine over sema and signal-sema"
publish      = false

[lib]
name = "sema_engine"
path = "src/lib.rs"

[dependencies]
blake3 = "1"
rkyv = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }
sema = { git = "https://github.com/LiGoldragon/sema.git", rev = "51d7927c872f0df12791bad8d39a4db6433b01a1" }
signal-frame = { git = "https://github.com/LiGoldragon/signal-frame.git", rev = "f46872e7e8edae5264c892443d415a273b231234", default-features = false }
signal-sema = { git = "https://github.com/LiGoldragon/signal-sema.git", rev = "4f3a24e6677ab9d200672851016c4c760c1e36e8", default-features = false }
thiserror = "2"

[dev-dependencies]
core-ethos = { git = "https://github.com/LiGoldragon/core-ethos.git", rev = "249ed6ac5b8a3a84fee5884bcb35b929f07e9166" }
core-nomos = { git = "https://github.com/LiGoldragon/core-nomos.git", rev = "a5e9aeeed90445a7df57ee1c4fda8e4be761b985" }
name-table = { git = "https://github.com/LiGoldragon/name-table.git", rev = "a22f48d8040ab9235f3552ad8654ff8e27b8157d" }
rust-logos = { git = "https://github.com/LiGoldragon/rust-logos.git", rev = "250e728fa9e5a02e3c9a6d4f0cfee0683863df83" }
schema-rust = { git = "https://github.com/LiGoldragon/schema-rust.git", rev = "9bd0767a387774ea70f8cf4b9b5e3d3617cf7671", default-features = false }
sema-translator = { git = "https://github.com/LiGoldragon/sema-translator.git", rev = "bc8410dfe4d449cc0e820a2c5b4d44496ad92acd", default-features = false, features = ["bootstrap"] }
signal-sema-translator = { git = "https://github.com/LiGoldragon/signal-sema-translator.git", rev = "3a26cb43f8ce7f9fe85da64d19aa55aa662943ce" }
structural-codec = { git = "https://github.com/LiGoldragon/structural-codec.git", rev = "413e3744569ca237e837a1fd57d9ba6ad6adc3de" }
tempfile = "3"

[lints.rust]
unsafe_code = "forbid"
unused = { level = "warn", priority = -1 }
dead_code = { level = "warn", priority = -1 }
