// @generated by schema-rust from an authority-verified bootstrap Sema

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct z2VKo1(std::string::String);
impl z2VKo1 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct z2VKo2 {
    pub field_0: z2VKo1,
    pub field_1: u64,
    pub field_2: std::string::String,
}
pub struct z2VKo3;
impl sema_engine::TableSpecification for z2VKo3 {
    type Record = z2VKo2;
    type Key = z2VKo1;
    const TABLE_NAME: sema_engine::TableName = sema_engine::TableName::new("z2VKo3");
    const FAMILY_NAME: &'static str = "z2VKo3";
    const SCHEMA_HASH: sema_engine::SchemaHash = sema_engine::SchemaHash::new([
        199, 207, 67, 102, 195, 131, 30, 219, 59, 19, 153, 4, 179, 56, 222, 133, 25, 80,
        186, 112, 200, 223, 251, 94, 183, 111, 171, 172, 194, 216, 16, 218,
    ]);
    fn record_key(key: &Self::Key) -> sema_engine::Result<sema_engine::RecordKey> {
        Ok(sema_engine::RecordKey::new(key.payload().to_string()))
    }
}
